### ISSUE TITLE
Migrate CI from `main` to all `dev-*`/`release-*` branches

### ISSUE THREAD

**Issue by CodeGat** [ACCESS-NRI/access-om3-wav-configs#55]
Since `on.pull_request` workflows only work if they are in either the source or target branch of a pull request, we need to move the CI files into all the `dev-*` and `release-*` branches in this repository in order for it to fire. 

Similar to ACCESS-NRI/access-om3-configs#138

**Comment by CodeGat** [comment]
So would this issue be a good use of the `!cherry-pick` command, then? @anton-seaice

**Comment by anton-seaice** [comment]
You'll need to make the first PR (into dev-1deg_jra55do_ryf) the old fashioned way. Should be able to use cherry-pick for the second

**Comment by CodeGat** [comment]
Closing this as the above are merged
